//Server/client consts

BLUE_COLOR = '#2166dd';
BLUE_FILL = '#2166dd';
RED_COLOR = '#980e2e';
RED_FILL = '#980e2e';

MIN_NODE_DISTANCE = 10;

BASE_HEALTH_MULTIPLY_CONST = 30;
NEUTRAL_NODE_HEALTH = 10;

ATTACK_COOLDOWN = 3;
HEAL_COOLDOWN = 10;

SCOUT_DAMAGE = 10;
TANK_DAMAGE = 30;
MEDIC_DAMAGE = 2;

SCOUT_CAPTURE_LIFE = 35;
MEDIC_CAPTURE_LIFE = 15;
TANK_CAPTURE_LIFE = 5;

MEDIC_HEAL = 20;
